cluster-cancel: scancel %j
cluster:
  sbatch
    --partition={resources.slurm_partition}
    --account={resources.slurm_account}
    --nodes={resources.nodes}
    --time={resources.time}
    --mem={resources.mem_mb}
    --ntasks-per-node={resources.ntasks}
default-resources:
  - slurm_partition=teach_cpu
  - slurm_account=sscm037184
  - mem_mb=100
  - time="30:00"
  - ntasks=1
  - nodes=3
jobs: 1
printshellcmds: True
scheduler: greedy
use-conda: True
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 3
latency-wait: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True