cluster-cancel: scancel %j

cluster:
  sbatch: |
    --partition={resources.slurm_partition}
    --account={resources.slurm_account}
    --nodes={resources.nodes}
    --ntasks-per-node={resources.ntasks_per_node}
    --cpus-per-task={resources.cpus_per_task}
    --time={resources.time}
    --mem={resources.mem_mb}

default-resources:
  slurm_partition: teach_cpu
  slurm_account: sscm037184
  mem_mb: 100
  time: "00:30:00"
  ntasks: 1
  nodes: 1

jobs: 4
printshellcmds: True
scheduler: greedy
use-conda: True
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 10
keep-going: True
rerun-incomplete: True
