name: env_2725312
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake=7.26
  - graphviz
  - curl
  - xmllint
  - r-base=4.3
  - r-tidyverse
  - r-ggplot2
  - r-xml2
  - r-tm
  - r-stopwords
  - r-tidytext
  - r-textstem
  - r-topicmodels
  - r-stm
  - r-Rtsne
  
